### ISSUE TITLE
After updating to v1.0.3, the display is distorted in live preview mode.

### ISSUE THREAD

**Issue by FScoward** [Bluemoondragon07/Obsidian-Serenity#11]
Thank you for providing an excellent theme. I really love it, but after the v1.0.3 update, the display has become distorted.

![image](https://github.com/Bluemoondragon07/Obsidian-Serenity/assets/1255521/2adb0bd1-5852-42e8-931f-a5d31ff6078c)

```css
/* make edit mode use a different readable line length than reading mode */
  .markdown-source-view.mod-cm6.is-readable-line-width .cm-sizer,
  .markdown-source-view.mod-cm6.is-readable-line-width .cm-content,
  .markdown-source-view.mod-cm6.is-readable-line-width .cm-line  {
    width: var(--editing-file-line-width) !important;
    margin: auto;
    padding: 0;
  }
```

↓ Removing "margin: auto;" resolves the display distortion issue.

```css
/* make edit mode use a different readable line length than reading mode */
  .markdown-source-view.mod-cm6.is-readable-line-width .cm-sizer,
  .markdown-source-view.mod-cm6.is-readable-line-width .cm-content,
  .markdown-source-view.mod-cm6.is-readable-line-width .cm-line  {
    width: var(--editing-file-line-width) !important;
    padding: 0;
  }

```

![image](https://github.com/Bluemoondragon07/Obsidian-Serenity/assets/1255521/22178754-c761-4ed5-96d4-26b0f95fce61)
