### ISSUE TITLE
Properties has become difficult to access

### ISSUE THREAD

**Issue by Noffica** [Bluemoondragon07/Obsidian-Serenity#25]
_Properties_ have become quite difficult to access. They can only be viewed under mouse-over, and attempts to add new ones, using the mouse, fail as the _properties_ section collapses / hides away.

See screen recording attached. 

https://github.com/Bluemoondragon07/Obsidian-Serenity/assets/6937598/a5579dff-8e86-437e-a460-a665b0bd44d9

Please forgive my gratuitous use of exclamation marks.

I see no such issues with other themes e.g. "Default" or "Atom". See screenshot here: 
![CleanShot 2023-12-22 at 18 48 27](https://github.com/Bluemoondragon07/Obsidian-Serenity/assets/6937598/4abeb249-6d7c-425e-bb81-fd29bf91975d)

```
About Obsidian
Version 1.4.16 (Installer 1.4.13)
```

```
Serenity
v2.0.8
```

**Comment by kumar7vaibhav** [comment]
You can try removing the hover properties section from the code.

**Comment by Noffica** [comment]
I have very little working knowledge of HTML, CSS and front end development, so could you specify the exact lines

**Comment by kumar7vaibhav** [comment]
There would be section in theme.css file - `/* Hover Frontmatter */`. Comment or remove that entire section from the code. After that reload the application again and you will find the frontmatter in default format.
![image](https://github.com/Bluemoondragon07/Obsidian-Serenity/assets/75883783/98518a29-47a2-4311-8f70-292c63400c36)

**Comment by Noffica** [comment]
The issue has arisen once again. If I delete or comment-out the following lines…

```css
/* Hover Frontmatter */
body:not(.normal-prop) [data-type=markdown] .metadata-container:not(:hover) .metadata-content, body:not(.normal-prop) [data-type=markdown] .metadata-container:not(:hover) .metadata-property, body:not(.normal-prop) [data-type=markdown] .metadata-container:not(:hover) .metadata-add-button.text-icon-button {
    display: none;
}
body:not(.normal-prop) [data-type=markdown] .metadata-container.is-collapsed:hover .metadata-content {
    display: unset !important;
}
body:not(.normal-prop) [data-type=markdown] .metadata-container.is-collapsed:hover .metadata-properties .metadata-property  {
    display: flex !important;
}
```

then I see such clashes of UI elements:
![2025-01-14~02 54](https://github.com/user-attachments/assets/c5d9e5e2-1be3-40c3-8139-e2c2739989ae)


```
About Obsidian
Version 1.7.7 (Installer 1.6.7)
```

```
Serenity
v2.0.9
```
