### ISSUE TITLE
[Styles] Some selectors result in sidebar brakes

### ISSUE THREAD

**Issue by servertdot** [Bluemoondragon07/Obsidian-Serenity#26]
Hi, found some selectors that cause brakes in the sidebar

1) 
```css
/* remove normal cursor when ninjacursor is installed */
body:not(:not(.iA-cursor)):has(.x-cursor) .cm-editor * {
caret-color: transparent;
}
```

2)
```css
.pure-md:has([data-mode="source"] .markdown-source-view:not(.is-live-preview)) .cm-editor *:not(.inline-title) {
font-size: var(--font-text-size) !important; 
}
```

Obsidian: 1.5.8
System: MacOS Sonoma 14.0 

![serenity-freeze](https://github.com/Bluemoondragon07/Obsidian-Serenity/assets/73301055/639aa133-694b-4b6c-aba4-5a296e61bdf3)
